### ISSUE TITLE
Add documentation about formatTime

### ISSUE THREAD

**Issue by toh82** [toh82/hbs-blog#6]
the documentation for this helper is missing and should be added to the readme.
Also, provide an example on how to use the helper.

---
- [x] claim issue (@jklepatch)
- [x] create a fork form of the repo
- [x] add documentation and example
- [x] open a pull request

**Comment by jklepatch** [comment]
@toh82 want some help for that?

**Comment by toh82** [comment]
@jklepatch Sure, that would be stellar.
Could you create a fork and a PR to this Repo?

**Comment by jklepatch** [comment]
Done: https://github.com/toh82/hbs-blog/pull/8

**Comment by toh82** [comment]
Resolved with PR #8
